name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore DevOpsDemo.csproj
      
    - name: Build
      run: dotnet build DevOpsDemo.csproj --configuration Release --no-restore
      
    - name: Run tests
      run: dotnet test tests/DevOpsDemo.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Publish test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/test-results.trx'

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Run code formatting check
      run: dotnet format --verify-no-changes --verbosity diagnostic

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, code-analysis]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/devops-demo-dotnet
        tags: |
          type=raw,value=latest
          type=sha,prefix={{branch}}-
          type=semver,pattern={{version}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILD_CONFIGURATION=Release
          
    - name: Image digest
      run: echo "Image pushed with digest ${{ steps.docker.outputs.digest }}"

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy notification
      run: |
        echo "Deployment would happen here"
        echo "In a real scenario, this would:"
        echo "- Deploy to Azure App Service / AWS ECS / Kubernetes"
        echo "- Pull the latest Docker image"
        echo "- Update the running containers"
        echo "- Run health checks"
        echo "- Rollback if health checks fail"
        
    - name: Post-deployment health check
      run: |
        echo "Health check simulation"
        echo "curl -f http://your-app-url/health || exit 1"
